[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 20

[environments.production.variables]
ENVIRONMENT = "production"

[environments.production.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60