[build]
builder = "nixpacks"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 60
watchPatterns = ["**/*.py"]

[environments.production.variables]
ENVIRONMENT = "production"

[environments.production.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60