services:
  - type: web
    name: auge-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MAIN_GROUP_CHAT_ID
        sync: false
      - key: DUVIDAS_GROUP_CHAT_ID
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
    autoDeploy: true
    healthCheckPath: /